apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dep
  labels:
    app: mongodb-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pod
  template:
    metadata:
      labels:
        app: mongodb-pod
    spec:
      containers:
      - name: mongodb-cont
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_RDATABASE
          value: db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-pod
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
