apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-dep
  labels:
    app: server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-pod
  template:
    metadata:
      labels:
        app: server-pod
    spec:
      containers:
      - name: server-cont
        image: iahs5/book-store-server:1.0
        ports:
        - containerPort: 5137
        env:
        - name: MONGO_USERNAME
          value: root
        - name: MONGO_PASSWORD
          value: root
        - name: MONGO_PORT
          value: '27017'
        - name: SERVER_PORT
          value: '5137'
        - name: HOST
          value: mongodb-service
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-pod
  type: NodePort 
  ports:
    - protocol: TCP
      port: 5137
      targetPort: 5137
      nodePort: 30002
